# -*- coding: utf-8 -*-
"""Gopi Nath V

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1INGHKykBNXdbJxklTk7O-hp4sQz41pGl
"""

def household():
   print("\n Calculating household Eb price")
   unit=int(input("\n number of units used:"))
   if unit<100:
        price=0.50
        print("your price : Rs",price)
   elif unit>101 and unit<200:
        price = unit*0.75
        print("your price : Rs", price)
   elif unit>201 and unit<300:
        price = unit*1.20
        print("your price : Rs", price)
household()

print("""I am signing up for Replit's 100 days of Python challenge! I will make sure to spend
some time every day coding along, for a minimum of 10 minutes a day. I'll be using
Replit, an amazing online IDE so I can do this from my phone wherever I happend to be.
No excuses for not coding from the middle of a field!""")

malware={'skyhigh':'SH','Tonjan':'T virus','filehouse':'loop ware','kaspersky':'k7'}
print(malware)
print(malware.values())
print(malware.items())
print(malware.keys())
print(malware.clear())

the_height = float(input("Enter the height in cm: "))  
the_weight = float(input("Enter the weight in kg: "))  
the_BMI = the_weight / (the_height/100)**2  
print("Your Body Mass Index is", the_BMI)  

if the_BMI <= 18.5:  
    print("Oops! You are underweight.")  
elif the_BMI <= 24.9:  
    print("Awesome! You are healthy.")  
elif the_BMI <= 29.9:  
    print("Eee! You are over weight.")  
else:  
    print("Seesh! You are obese.")

import pandas as pd
import pandas as pd
df=pd.DataFrame ({'offence':['sending threatning messages by email','sending defamatory messages by email','forgery or electronic records','bogus website cyber frauds','email spoofing','web jacking','email abuse','online sale of drugs','online sale of arms'],
                   'law':['sec 503 ipc','sec 499 IPC','sec 463 IPC','sec 420 ipc','sec 463 IPC','sec 383 IPC','sec 500 IPC','NDPS','arms act'],'penalties':['jail for 4 month','fine 50000','fine 60000','fine 10000','fine 40000','fine 50000','jail for 1year','jail for 2years','fine 20000']})
print(df)

mc=12300
gst="18%"
gsta=12300*18/100
print("GST amount of the mobile:",gsta)
na=mc+gsta
print("Net Price:",na)

import pandas as pd
data = {
"name": ['gopi', 'deva', 'venky', 'kalai', 'kumar', 'sudhan', 'dhina', 'arthi', 'ramesh', 'surya'],
"date": [2005, 2002, 2002, 2010, 2000, 2009, 2010, 2012, 2013, 2015,],
"weigh": ['60kg', '70kg', '50kg', '45kg', '60kg', '80kg', '30kg', '20kg', '20kg', '40kg',],
"height": ['120cm', '100cm', '80cm', '60cm', '90cm', '80cm', '60cm', '130cm', '175cm', '165cm',]
}
df=pd.DataFrame(data)
df['age']=2022-df['date']
df['health status']=df['age'].apply (lambda X:'critical' if X>58 else 'normal')
print (df)